On-prem build + tests

diff --git a/scripts/cheese b/scripts/cheese
--- a/scripts/cheese
+++ b/scripts/cheese
@@ -3,7 +3,7 @@
 ALL_ARGS=$@
 
 command=$1
-
+test_component=$2
 
 VALIDATE_SMILES="false"
 CANONICALIZE_SMILES="false"
@@ -103,8 +103,45 @@ else
         else
             cheese-embeddings --input_file $input_file --dest $INFERENCE_OUTPUT_DIR --search_types $SEARCH_TYPES --gpu_devices $GPU_DEVICES --save_format $save_format;
         fi
+    
+
+
+    elif [ "$command" = "test" ]; then
+        sudo rm -rf /tmp/cheese_test
+        mkdir /tmp/cheese_test
+        if [ "$test_component" = "cli" ]; then
+
+            # Start CHEESE CLI and generate test script
+            docker run -u root --entrypoint "python" -v /:/data --env PORT=$DB_PORT --env CONFIG_FILE=/data/$CONFIG_FILE --env LICENSING=True --env CHEESE_LICENSE_FILE=/data/$LICENSE_FILE --env TRANSFORMERS_CACHE=/tmp --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app();' $ALL_ARGS
+            bash /tmp/cheese_test/test_cheese_cli.sh
+
+        elif [ "$test_component" = "api" ]; then
+
+        echo "Starting app for testing"
+        cheese-app test
+
+        # Define Endpoints
+        DB_URL="http://"$IP":$DB_PORT"
+        API_URL="http://"$IP":$API_PORT"
+        UI_URL="http://"$IP":$UI_PORT"
+
+
+        echo "Removing existing API container"
+        docker rm -f api
+
+        echo "Testing API"
+        API_CONTAINER="${USER}_api_test"
+        docker run -u root -v /:/data --env API_URL=$DB_URL --env UI_URL=$UI_URL --env PORT=$API_PORT --env CONFIG_FILE=/data/$CONFIG_FILE --env LICENSING=True --env CHEESE_LICENSE_FILE=/data/$LICENSE_FILE --name $API_CONTAINER --entrypoint bash -p $API_PORT:$API_PORT --rm $API_IMAGE -c "cd tests; pytest"
+
+
+        else
+            echo "Error ! Please specify the component you want to test : 'cli' or 'api'."
+            exit 1  
+        fi
 
     else
-        docker run -u $UID -it --entrypoint "python" -v /:/data --env PORT=$DB_PORT --env CONFIG_FILE=/data/$CONFIG_FILE --env LICENSING=True --env CHEESE_LICENSE_FILE=/data/$LICENSE_FILE --env TRANSFORMERS_CACHE=/tmp --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app();' $ALL_ARGS
+    # Run other commands in CHEESE CLI
+    docker run -u $UID -it --entrypoint "python" -v /:/data --env PORT=$DB_PORT --env CONFIG_FILE=/data/$CONFIG_FILE --env LICENSING=True --env CHEESE_LICENSE_FILE=/data/$LICENSE_FILE --env TRANSFORMERS_CACHE=/tmp --rm $DB_IMAGE -c 'import cheese_database.cheese_cli as cli; cli.app();' $ALL_ARGS
+
     fi
 fi
